### DISCUSSION TITLE
`shasum` hash mismatch on CI

### DISCUSSION THREAD

**Discussion by shamoilarsi** [MetaMask/snaps#2933] [Q&A] [answered]
Hey, I'm facing a build issue with my Snap package in GitHub Actions CI. The `shasum` hash generated during the CI build doesn't match the one stored in the repository, causing build failures when checking for a clean working directory. I'm using the default workflow that comes with `@metamask/create-snap` for the most part with minor env changes

I assume skipping the `"Require clean working directory"` step would not be a valid solution and a short discussion of the Consensys Discord server confirmed it.

Here is what the workflow looks like - 
```yml
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install Yarn dependencies
        run: yarn --immutable

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn --immutable --immutable-cache
      - run: yarn build
      - name: Cache snap build
        uses: actions/cache@v3
        with:
          path: ./packages/snap/dist
          key: snap-${{ runner.os }}-${{ github.sha }}
      - name: Require clean working directory # <-- failing
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

```

Could this mismatch possibly be because of different operating systems? The CI uses ubuntu while I'm using MacOS locally.

Thanks in advance!
